services:
  frontend:
    image: ghcr.io/himanshubisht1606/posttrade-frontend:dev-latest
    container_name: posttrade-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:80"
    mem_limit: 128m
